def select_emoticon(x):
    return {
        ":)" : 'happy',
        ":(" : 'sad',
        ":o" : 'surprised',
        ":-*" : 'kizz',
        ":-D" : 'laugh',
        ">:-o" : 'angry',
        "=D>" : 'applause',
        ">:D<": 'hug',
        ":-\\": 'undecided',
        ":-|" : 'whatever',
        ";-)" : 'wink',
        "8-)" : 'cool',
        ":'(" : 'cry',
        "<:-|": 'foolish',
        ":-!" : 'foot in mouth',
        "X;{" : 'sick',
        ":D" : 'big grin',
        "😍":'heart',
        "😂":'smile',
        "😎":'smile',
        "✌":'victory',
        "🔫":'',
        "👉":'point',
        "😁":'smile',
        "😘":'kiss',
        "🤗":'hug',
        "🤩":'',
        "<3":'heart',
        "😶":'',
        ":D":'',
        "...":'',
        "😥":'cry',
        "😨":'fear',
        "🙄":'think',
        "😑":'expressionless',
        ":)":'smile',
        "ð":'',
        "Ÿ":'',
        "˜‰":'',
        ":p":'',
        "¤":'',
        "❤":'heart'

    }.get(x, x)